/*!
* Vietrick Apps https://www.vietrick.com/apps/
* A Vietrick Apps
* @version 1.0.5
* @author Lê Hòa <vietrick.com@gmail.com> (https://github.com/vietrick)
* @license: MIT
*/var request;$("#getlink").submit(function(event){disable_btn();$("#results").html("");event.preventDefault();if(request){request.abort();}
var $form=$(this);var $inputs=$form.find("input");var n=$inputs.val().trim();var serializedData=$form.serialize();try{$inputs.prop("disabled",true);if(-1!=n.indexOf("nhac.vn/bai-hat/")){api='nhac.vn.php';var type='audio';CORS_meta();}else{$inputs.prop("disabled",false);$("#results").hide();$("#results").html("<p>Không hỗ trợ link này!</p>");resume_btn();$("#results").slideToggle("slow");return!1;}
request=$.ajax({url:'../library/'+api,type:"post",timeout:5000,data:serializedData});request.done(function(response,textStatus,jqXHR){$inputs.val("");resume_btn();jsonData=jqXHR.responseJSON;if(jsonData.code==0){if(type!='doc'){var html=mplayer(jsonData,api);$("#results").html(html);}else{var html=ddoc(jsonData);$("#results").html(html);}}else{$("#results").html("<b>Không thể get được link này!</b><br/> Vui lòng thông báo dưới comment để được hỗ trợ.");}
$("#results").hide();$("#results").slideToggle("slow");});request.fail(function(jqXHR,textStatus,errorThrown){$("#results").html("<b>Máy chủ đang bận</b>.");console.error("The following error occurred: "+
textStatus,errorThrown);});request.always(function(){$inputs.prop("disabled",false);});}catch(err){$("#results").html("<b>Không thể get được link này!</b><br/> Vui lòng thông báo dưới comment để được hỗ trợ.");console.log("Error: "+err);}});function resume_btn(){$("#submit").prop("disabled",false);$("#submit").html('Get Link');$("#submit").attr("class","btn btn-danger mb-2 col-sm-2");}
function disable_btn(){$("#submit").prop('disabled',true);$("#submit").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class="sr-only">Loading...</span>');$("#submit").attr("class","btn btn-default mb-2 col-sm-2");}
function CORS_meta(){if(!($('meta[name="referrer"]').length))$("head").append('<meta name="referrer" content="no-referrer" />');}
has_forbid=['nixcdn.com/waiting_approve'];function mplayer(data,api){if(typeof(data.video)=='undefined'){var download_icon='<svg width="1.25rem" height="1.25rem" viewBox="0 0 16 16" class="bi bi-cloud-arrow-down-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2zm2.354 6.854l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7.5 9.293V5.5a.5.5 0 0 1 1 0v3.793l1.146-1.147a.5.5 0 0 1 .708.708z"/></svg>';var html='<div class="m-player row"><div class="player-cover col-sm-4"><img class="img-fluid mx-auto d-block rounded mb-4 shadow-lg bg-light lazyload" style="max-height: 300px" data-src="'+data.audio.cover+'" alt="'+data.audio.title+'"></div><div class="player-info col-sm-8"><div class="song-info"> <div class="song-info"> <h3>'+data.audio.title+'</h3> <h4 class="text-muted">'+data.audio.singer+'</h4> </div><div class="player-control mb-2"><audio class="col-sm px-0" id="player" controlsList="nodownload" controls autoplay loop><source src="'+data.audio.play+'" type="audio/mp3"/> </audio> </div>';html+='<div class="player-download">';html+='<a class="btn btn-info waves-effect waves-light btn-rounded mr-2 mb-2" download="'+data.audio.title+'-sd" target="_banks" title="128kbps" href="'+data.audio['128kbps']+'">'+download_icon+' 128kbps </a>';if(data.audio['320kbps'].length>10){html+='<a class="btn btn-warning mr-2 mb-2" download="'+data.audio.title+'-hq" target="_banks" title="320kbps" href="'+data.audio['320kbps']+'">'+download_icon+' 320kbps </a>';}
if(data.audio.lossless.length>10&&!(has_forbid.some(i=>(-1!=data.audio.lossless.indexOf(i))))){html+='<a class="btn btn-success waves-effect waves-light  mr-2 mb-2" download="'+data.audio.title+'-lossless" target="_banks" title="FLAC" href="'+data.audio.lossless+'">'+download_icon+' Lossless </a>';}else{html+='<a class="btn btn-secondary disabled" download="'+data.audio.title+'-lossless" target="_banks" title="FLAC" href="'+data.audio.lossless+'">'+download_icon+' Lossless </a>';}
html+='</div></div></div>';}
return html;}
